# Generated by Django 2.2.5 on 2020-09-20 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_organizer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
