# Generated by Django 2.2.5 on 2020-09-20 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
