# Generated by Django 2.2.5 on 2020-09-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='tickets',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
