# Generated by Django 2.2.5 on 2020-09-23 05:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_booking_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 23, 5, 29, 43, 155351, tzinfo=utc)),
        ),
    ]
